# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd3d01ab5242195994c4fb06b6d71df6edf429df90dc3ec6ec547c4f04e8b95a081e15e9877ea37f1ee72af6bd8c25e031968f1c8e4bb49fef8730c5d1514939

test:
  secret_key_base: 952aa970fd1128271c6308fc24679cca40798d3ee1e907e34280f250900c1ff7ecd0530b5821ca2fb20b2c4930a189d52eaef264c6a2c9b2a02dec3ad46b62ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
